development:
  adapter: postgresql
  encoding: unicode
  database: redditplica_development
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: redditplica_test
  pool: 5
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: redditplica_production
  password:
